javascript:
/* removes prefixes from birth and death locations generated by FamilySearch*/
birth = document.getElementById('mBirthLocation');
birth.value = removeCrap(birth.value);

death = document.getElementById('mDeathLocation');
death.value = removeCrap(death.value);

function removeCrap(input)
{
	return input
	.replace("Bezirksamt ", "")
	.replace("Kreis ", "")
	.replace("Amt ", "")
	.replace("Großherzogtum ", "")
	.replace("Republik ", "")
	;
}
void(0);